### PR TITLE
fix(string-decode): add decoding support for ISO 8859-1

### PR DESCRIPTION
**Pull request by kfenner**
ISO 8859-1 is also known as Latin-1

We need this for the old Desigo PX controllers!

### CODE REVIEW

**Comment by kfenner** [comment]
Hey @fh1ch: How do we want to handle different encoding types when writing? In the JSON world, everything is UTF-8 so the clients don't care. But what happens when we want to write a value back to the device? We would need to convert the UTF-8 string to the original encoding. I already identified the methods I'd need to change, but it's not clear to me, how I even get to know which encoding to set.

**Comment by fh1ch** [comment]
@kfenner first of all, thank you very much for this contribution. Since the supported set of encodings in Node.JS is quiet small, this stack doesn't support all the encodings specifiedby BACNET. I'm also not entitely sure if only the latin-1 subset is supported by BACNET as there is no '-1' postfix in the specs (see https://de.m.wikipedia.org/wiki/ISO_8859). However, I think we can give it a try...

LGTM 👍 

---

Regarding the writing: I think we have to expose the encoding parameter as well when reading strings (simmilar to the encodin type when reading a property value). We simply pass it then to the write call and ensure that way full interoperability. Your thought on this?

Please add this to the additional festure list at #28

**Comment by kfenner** [comment]
Had some doubts too regarding ISO 8859-1 but BACnet spec states it explicitely: http://www.bacnet.org/Addenda/Add-135-2008k.pdf

image

**Comment by kfenner** [comment]
Regarding the writing: I checked in our C++ implementation and it is exactly like this: The encoding is retrieved and stored while reading and then later used when writing. I will do the changes...

**Comment by fh1ch** [comment]
> I will do the changes...

@kfenner awesome, looking forward to it 👍

**Pull request merged**
